version: 0.2

env:
  variables:
    DOCKER_BUILDKIT: "1"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - docker pull $AWS_ECR_BUILD_REPOSITORY:latest
      - docker tag $AWS_ECR_BUILD_REPOSITORY:latest build:latest

      - IMAGE_TAG=$(echo ${CODEBUILD_RESOLVED_SOURCE_VERSION} | head -c 7)

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build --file Dockerfile --cache-from $REPO_URL:$REF_NAME --tag $REPO_URL:$REF_NAME .

  post_build:
    commands:
      - echo Build completed on `data`
      - echo Pushing the Docker image...
      - docker push $AWS_ECR_BUILD_REPOSITORY:$REF_NAME
      - echo "[{\"name\":\"rails\",\"imageUri\":\"${AWS_ECR_BUILD_REPOSITORY}:${REF_NAME}\"}]" > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - appspec.yml
    - taskdef.json