name: Run CodePipeline
on: [push]
env:
  REGION: ap-northeast-1
  PIPELINE_NAME: sample-rails-pipeline
jobs:
  deploy:
    needs: job1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS Credentials
      # v1
      uses: aws-actions/configure-aws-credentials@cefc5912bc61e2b5a3b049c839fc283c7712d4e0
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ${{ env.REGION }}
    - name: Trigger AWS CodePipeline
      uses: zulhfreelancer/aws-codepipeline-action@vX.X.X
      if: github.ref == 'refs/heads/your-branch-name'
      with:
        pipeline-name: ${{ env.PIPELINE_NAME }}